title: "Roommate Wanted - Midtown Plaza Champaign"
description: "Looking for a roommate for a modern 2BR/2BA apartment at Midtown Plaza, starting fall 2026. Park & pond views, perfect natural lighting, extra large balcony, modern furniture, massage chair and more!"
url: "https://xiaocong-yang.github.io"
baseurl: "/roommate-info"
image: "/roommate-info/img/header.jpg"
author: "Xiaocong Yang"
